# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0004_applause'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='audience',
            field=models.ManyToManyField(null=True, through='performances.Applause', to=settings.AUTH_USER_MODEL),
        ),
    ]
