# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_performance_audience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applause',
            old_name='musician',
            new_name='user',
        ),
    ]
