# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('instruments', models.CharField(choices=[('Unspecified', 'Unspecified'), ('Guitar', 'Guitar'), ('Violin', 'Violin'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard'), ('Voice', 'Voice')], default='Unspecified', max_length=100)),
            ],
            bases=('talent.talent',),
        ),
        migrations.AddField(
            model_name='talent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
