# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='musician',
            name='instruments',
        ),
        migrations.AddField(
            model_name='instrumenttag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Musician'),
        ),
        migrations.AddField(
            model_name='instrumenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_instrumenttag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='genretag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Musician'),
        ),
        migrations.AddField(
            model_name='genretag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_genretag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='talent.GenreTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
