# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:13
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('talent', '0003_auto_20170416_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='talent.GenreTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
