# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('talent', '0005_auto_20170416_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
            ],
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='MediumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Artist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_mediumtag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Artist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_styletag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='medium',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='talent.MediumTag', to='taggit.Tag', verbose_name='medium'),
        ),
        migrations.AddField(
            model_name='artist',
            name='style',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='talent.StyleTag', to='taggit.Tag', verbose_name='style'),
        ),
    ]
