# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_auto_20170515_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='talent_type',
            field=models.CharField(default='musician', max_length=100),
            preserve_default=False,
        ),
    ]
