# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0007_talent_talent_type'),
        ('applause', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=200)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='applausegf',
            name='style',
        ),
        migrations.RemoveField(
            model_name='applausegf',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='applausegf',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applausems',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='applausems',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='applausems',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='applausems',
            name='user',
        ),
        migrations.AlterField(
            model_name='genretag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applause.Applause'),
        ),
        migrations.AlterField(
            model_name='instrumenttag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applause.Applause'),
        ),
        migrations.AlterField(
            model_name='mediumtag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applause.Applause'),
        ),
        migrations.AlterField(
            model_name='styletag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applause.Applause'),
        ),
        migrations.DeleteModel(
            name='ApplauseGF',
        ),
        migrations.DeleteModel(
            name='ApplauseMS',
        ),
        migrations.AddField(
            model_name='applause',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='applause.GenreTag', to='taggit.Tag', verbose_name='genres'),
        ),
        migrations.AddField(
            model_name='applause',
            name='instruments',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='applause.InstrumentTag', to='taggit.Tag', verbose_name='instruments'),
        ),
        migrations.AddField(
            model_name='applause',
            name='style',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='applause.StyleTag', to='taggit.Tag', verbose_name='style'),
        ),
        migrations.AddField(
            model_name='applause',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Talent'),
        ),
        migrations.AddField(
            model_name='applause',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
