# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20170515_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='artist',
            new_name='talent',
        ),
    ]
