# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instrument', models.CharField(choices=[('Unspecified', 'Unspecified'), ('Guitar', 'Guitar'), ('Violin', 'Violin'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard'), ('Voice', 'Voice')], default='Unspecified', max_length=100)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
