# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artists.Artist')),
                ('instruments', models.CharField(choices=[('Unspecified', 'Unspecified'), ('Guitar', 'Guitar'), ('Violin', 'Violin'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard'), ('Voice', 'Voice')], default='Unspecified', max_length=100)),
            ],
            bases=('artists.artist',),
        ),
        migrations.AddField(
            model_name='instrumenttag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
        migrations.AddField(
            model_name='instrumenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_instrumenttag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='artist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='artists.InstrumentTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
